# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ReportPro - Easy Report"
client_id = "a53fcb46618232fcc1aca1bf585e700d"
application_url = "https://reportpro.codelocksolutions.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_customers,read_inventory,read_transactions,read_analytics"

[auth]
redirect_urls = [
  "https://reportpro.codelocksolutions.com/auth/callback",
  "https://reportpro.codelocksolutions.com/oauth_callback.php"
]

[webhooks]
api_version = "2026-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "customers/data_request" ]
  uri = "/webhooks/customers/data_request"

  [[webhooks.subscriptions]]
  topics = [ "customers/redact" ]
  uri = "/webhooks/customers/redact"

  [[webhooks.subscriptions]]
  topics = [ "shop/redact" ]
  uri = "/webhooks/shop/redact"

[pos]
embedded = false
