# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "ReportPro - Easy Report"
client_id = "a53fcb46618232fcc1aca1bf585e700d"
application_url = "https://reportpro.codelocksolutions.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products,read_customers,read_inventory,read_analytics,read_draft_orders,read_marketing_events,read_price_rules,read_discounts,read_shopify_payments_payouts,read_files,read_shopify_payments_disputes"

[auth]
redirect_urls = [
  "https://reportpro.codelocksolutions.com/auth/callback",
  "https://reportpro.codelocksolutions.com/oauth_callback.php"
]

[webhooks]
api_version = "2024-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"



[pos]
embedded = false
