# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "a53fcb46618232fcc1aca1bf585e700d"
name = "ReportPro - Easy Report"
application_url = "https://reportpro.codelocksolutions.com"
embedded = true

[webhooks]
api_version = "2026-01"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_inventory,read_orders,read_products"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://reportpro.codelocksolutions.com/oauth_callback.php",
  "https://reportpro.codelocksolutions.com/auth/callback"
]

[app_preferences]
url = "https://reportpro.codelocksolutions.com/settings"

